version: '3.2'
services:
  jenkins:
    image: myjenkins-blueocean:1.1
    privileged: true
    user: root
    ports:
      - 8082:8080
      - 5000:5000
    volumes:
      - /home/jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    networks:
      - jenkins
networks:
  jenkins:




